config/routes.rb
Rails.application.routes.draw do
  get 'returns/index'
  get 'projects/index'
  get 'projects/new'
  get 'projects/create'
  get 'homes/index'
  root to: 'homes#index'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users do
    collection do
      get 'profile'
    end
  end
  resources :projects do
    collection do
      get 'posts'
    end
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :purchases, only: [:index, :new, :create, :destroy] do
    collection do
      post 'confirm'
    end
  end
end

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul class="error_massage">
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p class="footer-text">&copy; <%= Time.current.year %> Copyright Shoma Cafe .</p>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="header-left-nav">
    <%= link_to (image_tag "logo.png", width:"200px", class: "logo-image"), root_path, data: {"turbolinks" => false}, class: "headerLogo" %>
    <div class="search_form">
      <%= search_form_for q, url: projects_path do |f| %>
        <%= f.search_field :title_cont, class: "searchBox", :placeholder => "キーワード" %>
        <%= f.submit "検索", class: "searchButton" %>
      <% end %>
    </div>
    <div class="mobile_search_form">
      <%= search_form_for q, url: projects_path do |f| %>
        <%= f.search_field :title_cont, class: "searchBox", :placeholder => "キーワード" %>
        <%= f.submit "検索", class: "searchButton" %>
      <% end %>
    </div>
    <%= link_to "プロジェクトをはじめる", projects_new_path, class: "project-start" %>
    <%= link_to "プロジェクトをさがす", projects_path, class: "project-search" %>
  </div>
  <div class="header-right-nav">
    <div onclick="obj=document.getElementById('open').style; obj.display=(obj.display=='none')?'block':'none';">
      <% if user_signed_in? %>
        <div class="userArea">
          <span class="user_name"><%= current_user.name %></span>
          <% if current_user.image? %>
            <%= image_tag current_user.image.url, class: "user-icon" %>
          <% else %>
            <%= image_tag "default.jpg", :size => '60x60', class: "user-icon" %>
          <% end %>
        </div>
    </div>
        <div id="open" style="display:none;clear:both;">
          <ul class="dropdown-menu">
            <li><%= link_to "プロジェクトをはじめる", projects_new_path, class: "menu-text" %></li>
            <li><%= link_to "作成したプロジェクト", posts_projects_path, class: "menu-text" %></li>
            <li><%= link_to "応援したプロジェクト", purchases_path, class: "menu-text" %></li>
            <li><%= link_to "プロフィール編集", profile_users_path, class: "menu-text" %></li>
            <li><%= link_to "メールアドレス・パスワード編集", edit_user_registration_path, class: "menu-text" %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "menu-text" %></li>
          </ul>
        </div>
      <% else %>
        <div class="nav-item">
          <%= link_to 'ゲストログイン', users_guest_sign_in_path, class: "log-in", method: :post %>
          <%= link_to 'ログイン', new_user_session_path, class: "log-in" %>
          <%= link_to '登録する', new_user_registration_path, class: "registration" %>
        </div>
        <div class="mobile-nav-item">
          <%= link_to 'ゲストログイン', users_guest_sign_in_path, class: "log-in", method: :post %>
          <%= link_to 'ログイン', new_user_session_path, class: "log-in" %>
          <%= link_to '登録する', new_user_registration_path, class: "registration" %>
        </div> 
      <% end %>  
  </div>
</header>