config/routes.rb
Rails.application.routes.draw do
  get 'returns/index'
  get 'projects/index'
  get 'projects/new'
  get 'projects/create'
  get 'homes/index'
  root to: 'homes#index'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users do
    collection do
      get 'profile'
    end
  end
  resources :projects do
    collection do
      get 'posts'
    end
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :purchases, only: [:index, :new, :create, :destroy] do
    collection do
      post 'confirm'
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :purchases
  has_many :returns, dependent: :destroy
  has_many :comments
  accepts_nested_attributes_for :returns, allow_destroy: true
  has_rich_text :content
  
  mount_uploader :image, ImageUploader
  mount_uploader :return_image, ImageUploader

  validates :title, presence: true
  validates :target_amount, numericality: true, presence: true
  validates :catch_copy_1, presence: true
  validates :catch_copy_2, presence: true
  validates :catch_copy_3, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :image, presence: true
  validates :content, presence: true
  validates_associated :returns

  validate :start_end_check
  validate :date_before_start

  def date_before_start
    return if start_date.blank?
    errors.add(:start_date, "は今日以降のものを選択してください") if start_date < Date.today
  end

  def start_end_check
    return if end_date.blank? || start_date.blank?
    errors.add(:end_date, "は開始日以降のものを選択してください") if end_date < start_date
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @projects = @q.result(distinct: true)
  end

  def new
    @project = Project.new
    @project.returns.build
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      flash[:notice] = "新規プロジェクトが作成されました"
      redirect_to posts_projects_path
    else
      render projects_new_path
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    @project.image.attach(params[:image]) if @project.image.blank?
    if @project.update(project_params)
     flash[:notice] = "プロジェクト内容を更新しました。"
     redirect_to posts_projects_path
    else
     render "edit"
    end
  end

  def show
    @project = Project.find(params[:id])
    @recommended_projects = Project.limit(4).order("RAND()").where.not(id: @project.id).where("start_date <= ?", Date.today).where.not("end_date < ?", Date.today)
    @comment = Comment.new
    @comments = @project.comments.order(created_at: :desc)
  end


  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "プロジェクトを削除しました"
    redirect_to posts_projects_path
  end

  def posts
    @projects = current_user.projects
  end

  def project_params
    params.require(:project)
    .permit(:title, :target_amount, :start_date, :end_date, :catch_copy_1, :catch_copy_2, :catch_copy_3, :image, :user_id, :purchase_id, :return_id, :content, :total_price,
    returns_attributes: [:return_image, :return_price, :return_name, :return_introduction, :_destroy])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def success_icon(project)
    if (@project.purchases.all.sum(:return_price).to_f / @project.target_amount.to_int * 100).round(0) >= 100 
      "Success!"
    end 
  end
end

app/views/projects/_catch_copy.html.erb
<section>
  <h3 class="catchCopyTitle">キャッチコピー</h3>
  <div class="catchCopyContainer">
    <ul>
      <li class="catchCopyText"><%= project.catch_copy_1 %></li>
      <li class="catchCopyText"><%= project.catch_copy_2 %></li>
      <li class="catchCopyText"><%= project.catch_copy_3 %></li>
    </ul>
  </div>
</section>

app/views/projects/_comment.html.erb
<section>
  <h3 class="catchCopyTitle">コメント</h3>
  <div class="commentContainer">
    <div class="commentFormArea">
      <% if current_user %>
        <%= form_with model:[@project, @comment] do |f| %>
          <p><%= f.text_area :message, autocomplete: "コメントする", :placeholder => "コメントを追加する", class: "commentForm" %></p>
          <div><%= f.submit "投稿", class: "commentSubmitButton" %></div>   
        <% end %>
      <% else %>
        <p>コメントを投稿するにはログインが必要です。</p>
      <% end %>
    </div>
      <% @comments.each do |comment| %>
        <div class="comment-content">
          <p>
            <% if comment.user.image? %>
              <%= image_tag comment.user.image.url, :size => '60x60', class: "profile-user-icon" %>
            <% else %>
              <%= image_tag "default.jpg", :size => '60x60', class: "profile-user-icon" %>
            <% end %>
          </p>
          <div class="comment-content-right">
            <p class="comment-user-name"><%= comment.user.name %></p>
            <% if current_user == comment.user %>
              <p class="comment-delete"><%= link_to "削除", comment, method: :delete, data: { confirm: "本当に削除しますか？" } %></p>
            <% end %>
            <p class="comment-message"><%= comment.message %></p>
          </div>
        </div>
      <% end %>
  </div>
</section>

app/views/projects/_hero_base.html.erb
<div class="heroBase">
  <div class="hero">
    <div class="projectImage">
      <%= image_tag project.image.to_s, class: "hero-image" %>
    </div>
    <div class="projectInfo">
      <div class="successIcon">
        <%= success_icon(project) %>
      </div>
      <div class="moneyTotal">
        <p class="moneyTotalText">応援購入総額</p>
        <p class="moneyTotalNum"><%= total_price %>円</p>
        <p class="moneyGoal">目標金額 <%= project.target_amount.to_s(:delimited) %>円</p>
        <div class="moneyMater">
          <%= success_rate %>%
          <progress id="myProgress" value=<%= success_rate %> max="100">0%</progress>
        </div>
      </div>
      <div class="supporter">
        <p class="supporterText">サポーター</p>
        <p class="supporterNum"><%= project.purchases.count %>人</p>
      </div>
      <div class="day">
        <p class="dayText">残り</p>
        <p class="dayNum">
          <% if  project.start_date.after? Date.today %>
            <p class="start-day"><%= project.start_date.strftime("%Y年 %m月 %d日") %></p><p class="startDayText">に開始予定です。</p>
          <% elsif project.end_date.before? Date.today %>
            終了
          <% else %>
            <%= (project.end_date - Date.today).to_int %>日
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="heroBtmBase">
  <div class="projectTitle">
    <p class="projectTitleText"><%= project.title %></p>
  </div>
</div>

app/views/projects/_left_content_main.html.erb
<h3 class="projectMainTitle">プロジェクト概要</h3>
<div class="leftContentMain">
  <%= project.content %>
</div>

app/views/projects/_profile.html.erb
<div class="userProfile">
  <h3 class="userProfileTitle">企画者のプロフィール</h3>
  <div class="balloon">
    <span class="userProfileText"><%= project.user.profile %></span>
    <div class="balloonTriangle"></div>
  </div>
  <div class="owner-profile">
      <% if project.user.image? %>
        <%= image_tag @project.user.image.url, :size => '60x60', class: "profile-user-icon" %>
      <% else %>
        <%= image_tag "default.jpg", :size => '60x60', class: "profile-user-icon" %>
      <% end %>
      <div class="profile-user-name"><%= project.user.name %></div>
  </div>
</div>

app/views/projects/_recommended.html.erb
<section class="recommendedBase">
  <div class="recommendedArea">
    <h3 class="recommendedTitle">その他のプロジェクト</h3>
    <div class="recommendedContainer">
      <% recommended_projects.each do |project| %>
        <div class="recommendedBox">
          <%= link_to project_path(project.id) do %>
            <div class="recommended-image-area">
              <% if project.image.blank? %>
                <%= image_tag "/assets/new_awazi.jpeg", class: "recommended-image" %>
              <% else %>
                <%= image_tag project.image.to_s, class: "recommended-image" %>
              <% end %>
            </div>
            <h4 class="recommended-title"><%= project.title %></h4>
            <div class="recommended-bottom">
              <div class="day-total">
                <% if  project.start_date.after? Date.today %>
                  <p>開始予定</p>
                <% elsif project.end_date.before? Date.today %>
                  終了
                <% else %>
                  残り<%= (project.end_date - Date.today).to_int %>日
                <% end %>
                <div class="recommended-total"><%= project.purchases.all.sum(:return_price).to_s(:delimited)  %>円</div>
              </div>
              <div class="return-bar">
                <progress id="myProgress" value=<%= (project.purchases.all.sum(:return_price).to_f / project.target_amount.to_int * 100).round(0) %> max="100">0%</progress>
              </div>
            </div>
          <% end %>
        </div>
      <% end %> 
    </div>
  </div>
</section>

app/views/projects/_return_fields.html.erb
<div class="nested-fields">
  <div class="field">
      <p class="projectNewTitle"><%= f.label :return_name ,"リターン名" %><span class="must">必須</span></p>
      <p><%= f.text_field :return_name, class: "textForm" %></p>
      <p class="projectNewTitle"><%= f.label :return_price, "価格" %><span class="must">必須</span></p>
      <p><%= f.number_field :return_price, class: "textForm" %></p>
      <p class="projectNewTitle"><%= f.label :return_introduction, "紹介文" %><span class="must">必須</span></p>
      <p><%= f.text_area :return_introduction, class: "IntroductionForm"  %></p>
      <p class="projectNewTitle"><%= f.label :return_image, "画像" %><span class="must">必須</span></strong>
      <p class="returnImageForm"><%= f.file_field :return_image %></p>
      <div class="returnDelete"><%= link_to_remove_association "リターンを削除する", f, class: "returnDeleteButton" %></div>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <%= render "shared/error", obj: @project %>
  <h3 class="postsTitle">プロジェクトの編集</h3>
  <div class="box">
    <%= form_with model: @project, local: true do |f| %>
      <p class="projectNewTitle"><%= f.label :title ,"プロジェクトタイトル" %></p>
      <p><%= f.text_field :title, class: "textForm" %></p>
      <p class="projectNewTitle"><%= f.label :catch_copy ,"キャッチコピー" %></p>
      <p class="catchCopyForm"><%= f.text_field :catch_copy_1, class: "textForm" %></p>
      <p class="catchCopyForm"><%= f.text_field :catch_copy_2, class: "textForm" %></p>
      <p><%= f.text_field :catch_copy_3, class: "textForm" %></p>
      <p class="projectNewTitle"><%= f.label :target_amount ,"目標金額" %></p>
      <p><%= f.number_field :target_amount, class: "textForm"  %></p>
      <p class="projectNewTitle">実施期間<p>
      <div>
        <p class="projectNewTitle"><%= f.label :start_date ,"開始日" %></p>
        <p><%= f.date_field :start_date, class: "textForm" %></p>
      </div>
      <div>
        <p class="projectNewTitle"><%= f.label :end_date ,"終了日" %></p>
        <p><%= f.date_field :end_date, class: "textForm" %></p>
      </div>
      <p class="projectNewTitle"><%= f.label :image, "プロジェクト画像" %></p>
      <p><%= f.file_field :image %></p>
      <div class="richTextForm">
        <p class="projectNewTitle"><%= f.label :content, "プロジェクト説明" %></p>
        <p><%= f.rich_text_area :content, class: "projectIntroductionForm" %></p>
      </div>
      <div class="returnAdd"><%= link_to_add_association "リターンを追加する", f, :returns, class: "returnAddButton" %></div>
      <p>※リターンは追加のみ可能です。</p>
      <div><%= f.submit "更新する", class: "returnSubmitButton" %></div>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <section class="recommendedBase">
    <div class="recommendedIndexArea">
      <h3 class="recommendedIndexTitle">プロジェクト一覧</h3>
      <h4 class="recommendedDisplay">表示件数：<%= @projects.count %>件</h4>
      <div class="recommendedIndexContainer">
        <% @projects.each do |project| %>
          <div class="recommendedBox">
            <%= link_to project_path(project.id) do %>
              <div class="recommended-image-area">
                <% if project.image.blank? %>
                  <%= image_tag "/assets/new_awazi.jpeg", class: "recommended-image" %>
                <% else %>
                  <%= image_tag project.image.to_s, class: "recommended-image" %>
                <% end %>
              </div>
              <h4 class="recommended-title"><%= project.title %></h4>
              <div class="recommended-bottom">
                <div class="day-total">
                  <% if  project.start_date.after? Date.today %>
                    <p>開始予定</p>
                  <% elsif project.end_date.before? Date.today %>
                    終了
                  <% else %>
                    残り<%= (project.end_date - Date.today).to_int %>日
                  <% end %>
                  <div class="recommended-total"><%= project.purchases.all.sum(:return_price).to_s(:delimited) %>円</div>
                </div>
                <div class="return-bar">
                  <%= (project.purchases.all.sum(:return_price).to_f / project.target_amount.to_int * 100).round(0) %>%
                  <progress id="myProgress" value=<%= (project.purchases.all.sum(:return_price).to_f / project.target_amount.to_int * 100).round(0) %> max="100">0%</progress>
                </div>
              </div>
            <% end %>
          </div>
        <% end %> 
      </div>
    </div>
  </section>
</div>

app/views/projects/new.html.erb
<div class="container">
  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>
  <%= render "shared/error", obj: @project %>
  <h3 class="postsTitle">プロジェクトをはじめる</h3>
  <div class="box">
    <%= form_with model: @project, method: :post, local: true do |f| %>
      <h3 class="projectNew">プロジェクトの登録</h3>
      <p class="projectNewTitle"><%= f.label :title ,"プロジェクトタイトル" %><span class="must">必須</span></p>
      <p><%= f.text_field :title, class: "textForm" %></p>
      <p class="projectNewTitle"><%= f.label :catch_copy ,"キャッチコピー" %><span class="must">必須</span></p>
      <p class="catchCopyForm"><%= f.text_field :catch_copy_1, class: "textForm" %></p>
      <p class="catchCopyForm"><%= f.text_field :catch_copy_2, class: "textForm" %></p>
      <p class="catchCopyForm"><%= f.text_field :catch_copy_3, class: "textForm" %></p>
      <p class="projectNewTitle"><%= f.label :target_amount ,"目標金額" %><span class="must">必須</span></p>
      <p><%= f.number_field :target_amount, class: "textForm"  %></p>
      <p class="projectNewTitle">実施期間<p>
      <div>
        <p class="projectNewTitle"><%= f.label :start_date ,"開始日" %><span class="must">必須</span></p>
        <p><%= f.date_field :start_date, class: "textForm" %></p>
      </div>
      <div>
        <p class="projectNewTitle"><%= f.label :end_date ,"終了日" %><span class="must">必須</span></p>
        <p><%= f.date_field :end_date, class: "textForm" %></p>
      </div>
      <p class="projectNewTitle"><%= f.label :image, "プロジェクト画像" %><span class="must">必須</span></p>
      <p><%= f.file_field :image %></p>
      <div class="richTextForm">
        <p class="projectNewTitle"><%= f.label :content, "プロジェクト説明" %><span class="must">必須</span></p>
        <p><%= f.rich_text_area :content, class: "projectIntroductionForm" %></p>
      </div>
      <h2 class="projectReturnRegi">リターンの登録</h2>
        <%= f.fields_for :returns do |r| %>
          <%= render "return_fields", f: r %>
        <% end %>
      <div class="returnAdd"><%= link_to_add_association "リターンを追加する", f, :returns, class: "returnAddButton" %></div>
      <div><%= f.submit "登録する", class: "returnSubmitButton" %></div>
    <% end %>
  </div>
</div>

app/views/projects/posts.html.erb
<div class="container">
  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>
  <h3 class="postsTitle">作成したプロジェクト一覧</h3>
  <% @projects.each do |project| %>
    <div class="postBox">
      <div class="postImageArea">
        <div><%= link_to (image_tag "#{project.image}", class: "postImage"), project_path(project.id) %></div>
      </div>
      <div class="postInfo">
        <div class="postTitle"><%= project.title %></div>
        <p class="moneyTotalNum"><%= project.purchases.all.sum(:return_price).to_s(:delimited)  %>円</p>
        <div class="postMoneyMater">
          <%= (project.purchases.all.sum(:return_price).to_f / project.target_amount.to_int * 100).floor(0).round(0) %>%
          <progress id="myProgress" value=<%= (project.purchases.all.sum(:return_price).to_f / project.target_amount.to_int * 100).round(0) %> max="100">0%</progress>
        </div>
        <div class="postDay">
          <% if  project.start_date.after? Date.today %>
            <%= project.start_date.strftime("%Y年 %m月 %d日") %>に開始予定です。
          <% elsif project.end_date.before? Date.today %>
            終了
          <% else %>
            残り<%= (project.end_date - Date.today).to_int %>日
          <% end %>
        </div>
      </div>
      <div class="postButton">
        <%= link_to "編集", edit_project_path(project), class: "postEdit" %>
        <%= link_to "削除", project, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "postDelete" %>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<% provide(:title, @project.title) %>
<%= render "shared/error", obj: @project %>
<div class="container">
  <%= render "hero_base", project: @project %>
  <div class="main">
    <div class="leftContent">
      <%= render "profile", project: @project %>
      <%= render "catch_copy", project: @project %>
      <%= render "left_content_main", project: @project %>
      <%= render "comment", comment: @comment %>
    </div>
    <div class="rightContent">
      <h3 class="returnTitle">リターン</h3>
      <%= render "purchases/new" %>
    </div>
  </div>
  <%= render "recommended", recommended_projects: @recommended_projects %>
</div>